#!/usr/bin/env node

"use strict";
var path = require('path'),
    fs = require('fs'),
    lib = path.join(path.dirname(fs.realpathSync(__filename)), '../lib/'),
    gen = require(lib + '/selectizer.min.js');

gen(process.argv[2], process.argv[3], function(a){
    if(!! a.success){
        a.generate();
    }
    else{
        console.log(a.data.errorMsg);
    }
});